#!/bin/sh

[ ! -e "/opt/local/dwm/bin/dwm" ] && { echo "dwm binary not found !"; exit 1; }

# relaunch DWM if the binary changes, otherwise bail
csum=""
new_csum=$(sha1sum /opt/local/dwm/bin/dwm)
while true; do
  if [ "$csum" != "$new_csum" ]; then
    csum=$new_csum
    /opt/local/dwm/bin/dwm >/tmp/dwm.log 2>/tmp/dwm.stderr.log
  else
    exit 0
  fi
  new_csum=$(sha1sum /opt/local/dwm/bin/dwm)
done

